@NewStart.Server_HostAddress = http://localhost:5028

GET {{NewStart.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{NewStart.Server_HostAddress}}/api/Game/
Accept: application/json

###